### ISSUE TITLE
Konnected Security Sensor no longer updates state in Homeassistant after updating to 2.2.7 release

### ISSUE THREAD

**Issue by slonkar** [konnected-io/konnected-security#100]
I recently upgraded my konnected security firmware on NodeMCU and since then it's not updating the state of the connected sensors. 

My config file looks like below. 

`#Konnected Security System
konnected:
  access_token: !secret konnected_access_token
  devices:
    - id: !secret konnected_motion_detectors
      binary_sensors:
        - pin: 1
          type: motion
          name: Kitchen Motion Detection
        - pin: 2
          type: motion
          name: Hallway Motion Detection
    - id: !secret konnected_door_window
      binary_sensors:
        - pin: 1
          type: door
          name: Front Door
        - pin: 2
          type: door
          name: Back Door
        - pin: 5
          type: door
          name: Deck Door
        - pin: 6
          type: window
          name: Dining Room Window
        - pin: 7
          type: window
          name: Family Room Window
        - pin: 9
          type: window
          name: Kitchen Window`

I checked sensors with a multimeter continuity test. They seem to be working fine. 

Homeassitant Configuration 

HassOS 2.12
HA Version - 0.96.5
DuckDNS with NGINX Home Assistant SSL proxy as recommended on this page - https://help.konnected.io/support/solutions/articles/32000023964-set-up-hass-io-with-secure-remote-access-using-duckdns-and-nginx-proxy

Let me know if any more information is needed. I will be happy to debug or provide logs.

**Comment by heythisisnate** [comment]
Make sure you have `discovery:` enabled also in your config so HA can find and re-sync the device.

This used to be enabled by default but a recent change in HA removed that from default components.
