### ISSUE TITLE
Enhancement: Improved discovery

### ISSUE THREAD

**Issue by iamandymcinnes** [konnected-io/konnected-security#107]
Hi,

I've recently started doing a lot more with ESPlib in home assistant and find it brilliant, adding new devices is a breeze and I love the way they show up in the integrations section of home assistant, as well as providing a whole host of functionality that just makes connecting, troubleshooting and seeing the status of your devices easier.

I wondered if there are any plans to adopt this approach with Konnected? Just as an example I built a doorbell with ESPlib with no prior knowledge of it or ESP devices in a couple of hours from scratch. Everything from the first flash of firmware using my home assistant machine, to easily deploying new code changes with the OTA feature were super easy and I had a nice UI to guide me through. 

Once a new device was added, I immediately got a notification in home assistant of the discovery of that device, and could then see a range of information on my new door bell, from IP address to MAC address and pin states to WIFI signal strength.

It would be awesome if we could do something similar with Konnected :)

Cheers

Andy

**Comment by heythisisnate** [comment]
I think this is a good idea. I need to play more with other ESP firmwares to see how we can improve.

Open source contributions are always welcome. We typically send out free product or swag for valuable contributions.
