### ISSUE TITLE
2.3.1 Release files reference 2.3.0 konnected-firmware-2-3-0.bin

### ISSUE THREAD

**Issue by iamandymcinnes** [konnected-io/konnected-security#108]
2.3.1 Release files reference 2.3.0 konnected-firmware-2-3-0.bin

https://github.com/konnected-io/konnected-security/releases

Not sure if this is a naming issue or the wrong file?

**Comment by heythisisnate** [comment]
The latest firmware is still 2.3.0. _Firmware_ refers to the underlying OS built on https://github.com/nodemcu/nodemcu-firmware

Only the Konnected application was updated in this release to 2.3.1.
