### ISSUE TITLE
is there a "standalone" rest API?

### ISSUE THREAD

**Issue by yeahman45** [konnected-io/konnected-security#119]
I don't want to use smartthings or other home automation systems but need a REST api for my own app. is there a REST api?

**Comment by heythisisnate** [comment]
Yes, see documentation here:
https://help.konnected.io/support/solutions/articles/32000026804-api-overview

**Comment by yeahman45** [comment]
thx! do you confirm that this works on LAN with no need of internet access?

**Comment by heythisisnate** [comment]
Yes, that's correct. Internet access is not required.
