### ISSUE TITLE
Temperature spikes with ds18b20 using konnected-temperature-probe-ds18b20.groovy

### ISSUE THREAD

**Issue by sapman1208** [konnected-io/konnected-security#133]
![100973911_10163844883490226_6041333648894984192_o](https://user-images.githubusercontent.com/35403072/83361307-e18ec800-a355-11ea-90b9-2311f3679a92.jpg)

I'm having an issue where certain temperatures readings with my ds18b20 are 1 degree higher only on certain temperature readings.
What should be:
89.7 reads 90.7
87.9 reads 88.9
86.1 reads 87.1
84.3 reads 85.3
This always happens on those temperature readings for me. This seems to be happening on 1.8 degree intervals.

**Comment by Korte68** [comment]
Hi,
As a workaround you can create a template sensor, which adjust the measured value:
Sensor:
 - platform: template
    sensors:
      newtemp:
        friendly_name: "New Temp"
        unit_of_measurement: '°C'
        value_template: "{{ states('sensor.originaltemp')|float - 2 }}"
