### ISSUE TITLE
SmartThings showing konnected PIR as incorrect type "placeholder"

### ISSUE THREAD

**Issue by daltskin** [konnected-io/konnected-security#134]
The sensors that show under the SmartThings devices have the wrong type set - they are being set to "placeholder".

Assuming these should be being set to "Motion Detector"
![konnected bug](https://user-images.githubusercontent.com/1678318/84906176-7a894700-b0a9-11ea-89c5-0c7d24ff7c04.png)

**Comment by heythisisnate** [comment]
This is not a bug. That's just how SmartThings new "cloud-to-cloud" device in the new platform show up in the old IDE. This does not indicate a problem.
