### ISSUE TITLE
Boot once and no boot on hard reset ... then boot again ?!?!?!

### ISSUE THREAD

**Issue by done7k** [konnected-io/konnected-security#136]
Very strange behavior.
a) flash a esp8266.. done ok; disconnect from usb; connect again
b) I connect to its wifi; go to 192.168.4.1; configure wifi connection; reboot - ok; 
c) it is connected to wifi; android app sees the device; I can http to it; while. it is attempting to connect to wifi it is blinking.
d) then disconnect from usb; connect to usb again; it blinks briefly.. and does not connect to wifi
e) I cannot even flash it - esptool (or arduino win/ubuntu no matter) does not see this device, however while connecting it is blinking .
I though it is dead.. but in some time ( 1 hour, 24 hours) it resumes from step (c) and then after a while "blocked" like at step (d) 
??? it is software issue or hardware??  it is connected to usb only, no sensors or other pin are used.

**Comment by heythisisnate** [comment]
Sorry, this is not a support forum.
