### ISSUE TITLE
On HA restart, state changes to "off" on sensors instead of "unavailable"

### ISSUE THREAD

**Issue by BigHomie90** [konnected-io/konnected-security#138]
Hi,

I have an automation on node red which fires when a state from a sensor changes from "off" to "on". The checkbox on node (trigger node) output on connect is unchecked.

When i restart home assistant the node starts because it detects state change from "off" to "on" even if the door was left at open state before and after the reboot of home assistant.

I saw from other sensors (xiaomi zigbee,tasmota etc.) that when i restart home assistant the state changes from the actual state to "unavailable" and then to the actual state again. Konnected changes from actual state to "off" while rebooting HA and then back to current state.

Am i doing something wrong? What can i do so when i restart home assistant, sensor does not go to "off" state?

Thank you.

**Comment by heythisisnate** [comment]
Haven't been able to reproduce this issue. When HA reboots, the device states will show Unavailable. It should't be transitioning to _off_ state during a reboot if the sensor hasn't changed.
