### ISSUE TITLE
Release 3.0.0 - Alarm Pro v2 - How do we perform a OTA upgrade of the firmware?

### ISSUE THREAD

**Issue by SeanHama** [konnected-io/konnected-security#157]
Hello

I'm confused on how to perform an OTA upgrade to get the latest firmware release? I'm hoping we don't have to physically flash the unit as my installation is not straight forward to access?

Im using RPI4 (Homebridge) and ipHone Konnected app?

**Comment by heythisisnate** [comment]
Unfortunately, upgrading to 3.0 will require a physical flash. We are working on a broader communication about this in the coming weeks. We're also releasing a new web-based flash tool at https://install.konnected.io to make this process as easy as possible. The web-based flash tool is currently fully functional, we just need to add some branding and guidance to the page.
