### ISSUE TITLE
Unable to update firmware on 1st panel of Alarm V2 - keeps saying connecting

### ISSUE THREAD

**Issue by SeanHama** [konnected-io/konnected-security#158]
<img width="870" alt="Screen Shot 2021-12-04 at 10 18 10 am" src="https://user-images.githubusercontent.com/57736130/144686394-92ec84f5-7249-48bc-9f30-dc7e2de5f823.png">

I have the Alarm v2 system.

Steps To Reproduce (Cable Im using ive previously upgraded panels with no problems).

1: Connected and upgraded the v3.0.1 firmware on the 2nd panel (worked first time).
2: Connected laptop to the 1st panel and all it does it say connecting? Any ideas on how to upgrade this panel please?

**Comment by awulff73** [comment]
It doesn't look like you have the Port which usually means you don't have a cord that can transmit data or you haven't installed the driver.

**Comment by SeanHama** [comment]
The cable works fine and transmit data, I updated the 2nd alarm panel just fine. And have previously used the cable to upgrade the panel which is not connecting now.

The port is appear correctly, what alternatives
Or options do I have?

**Comment by SeanHama** [comment]
Any ideas? My Konnected alarm is now not working correctly (the firmware is not the same on both boards) and the PIR sensors on the non-upgraded board not working.

**Comment by awulff73** [comment]
Submit a ticket to help@konnected.io with a screenshot of your device status.

**Comment by SeanHama** [comment]
done.

**Comment by iJuiceman** [comment]
Did this get sorted, what was the cause?
