### ISSUE TITLE
Push notification (HomeKit) when the system has been triggered, but before the Alarm is activated?

### ISSUE THREAD

**Issue by peterrakolcza** [konnected-io/konnected-security#162]
Hey!

I am using a NodeMCU 1.0 as my alarm system connected to my HomeKit system using Homebridge. I am looking for a way to receive a push notification when the system has been triggered, but before the Alarm is activated. Is that possible?

I know that I can have a zone set to a beeper, however I do not have a free zone...

Thanks!

**Comment by heythisisnate** [comment]
The Konnected Homebridge plugin is developed separately and open-source:
https://github.com/konnected-io/homebridge-konnected

Pull requests are welcome.
