### ISSUE TITLE
OTA update may fail while connected to AWS IoT

### ISSUE THREAD

**Issue by sadahsan** [konnected-io/konnected-security#170]
OTA update failure on 3.1.1
Tried few times to update through the konnected App but no luck.

**Comment by heythisisnate** [comment]
what version are you updating from?

**Comment by sadahsan** [comment]
App v3.0.1
Fw v3.0.0

Thanks

On 22 Aug 2022, at 14:28, Nate Clark ***@***.***> wrote:

﻿

what version are you updating from?

**Comment by heythisisnate** [comment]
I was able to reproduce this and determined that we run into a memory consumption issue when attempting to do an OTA (LFS) update while the device is connected to AWS IoT.

_Potential solution:_ Shut down persistent AWS IoT websocket connection prior to beginning OTA download/update. @h2zero 

_Workaround:_ Reset the device first before performing the update to clear the AWS IoT connection. Hold down the RESET button for ~10 seconds when the device is idle until the blue light comes on solid, then release the button. The device will reboot. Perform the OTA update. Then go back to the Konnected App -> device -> Manage Zones -> Sync to Device to re-provision the device to connect to Konnected Cloud (AWS IoT).

**Comment by sadahsan** [comment]
Thanks for looking into it so quickly, when do you expect to release the updated firmware with this fix?

**Comment by h2zero** [comment]
I'll have a PR ready in the next few hours. It won't help you to update from your current version though, you'll likely need to follow the workaround method Nate described above.

**Comment by sadahsan** [comment]
Ok thanks, will give it a go.

On 23 Aug 2022, at 00:13, h2zero ***@***.***> wrote:

﻿

I'll have a PR ready in the next few hours. It won't help you to update from your current version though, you'll likely need to follow the workaround method Nate described above.

**Comment by h2zero** [comment]
This may take a bit longer than expected. Closing the mqtt connection and disabling the associated timers is still not enough. This will require a more creative solution.

**Comment by h2zero** [comment]
That's what I was thinking as well. I tried everything else so far but didn't have time to try the file/reboot yet.
