### ISSUE TITLE
Security type

### ISSUE THREAD

**Issue by Craigzyc** [konnected-io/konnected-security#55]
What level of security is implemented in the communication between the smartthings hub and the device? 

I don't see anything mentioned about a security implementation but I figure there must be some decent encryption/security for a security device

**Comment by heythisisnate** [comment]
The device uses standard TLS encryption to talk to the SmartThings API to update the status of sensors as they change in real-time. The SmartThings hub communicates to the device (for actuating devices and device discovery/settings) over your local LAN via unencrypted HTTP messages.
