### ISSUE TITLE
Lux Sensor Enhancement Request

### ISSUE THREAD

**Issue by adamrhoades** [konnected-io/konnected-security#65]
Would it be possible to add functionality for a luminance sensor such as the TSL2561 or TSL2591?

I've been looking for a way to mount a lux sensor outside to govern lighting rules based on luminosity rather than timers and I find using local weather stations lux reading to be wildly unpredictable.

**Comment by vseven** [comment]
I know the DTH sensor was just added and I'm not sure about the roadmap for other sensors but you could do this with ST_Anything in the meantime (which this project was based on):   https://github.com/DanielOgorchock/ST_Anything

**Comment by heythisisnate** [comment]
This is a good idea, but not sure when I'll be able to get to it.
