### ISSUE TITLE
debounce?

### ISSUE THREAD

**Issue by henroFall** [konnected-io/konnected-security#72]
https://github.com/konnected-io/konnected-security/blob/b7b9ca5682a8bacf46d284dec1697666698b0411/src/application.lua#L79

For some reason, I have a couple of contacts that bounce and sometimes even stick open. I keep chasing a loose connection on the board but no luck solving it from that end.

I had attempted a webcore hack to debounce the switch before I realized the lag on events was too long to wait... So I think it needs to be in the lua.

I'll go down a rabbit hole on how to edit this script and compile it and so forth... Or maybe I can file copy it into my hardware, IDK... I'll probably just put in a simple delay between where this loop detects a state change and where it commits the changed value to the variable. I hope I can do this with a second or so delay.

If I get really bored I guess I'll figure out how to let the user specify the debounce time in ms somewhere but I'd have to google a lot to get that done.

Thanks for a great app!

Henry

**Comment by heythisisnate** [comment]
You really shouldn't need to debounce. Sounds to me like something is loose with your sensor wiring or weird with the sensor itself. Check the resistance on the wire loop with a multimeter, it should be close to zero.

You don't need to recompile the script. You can simply upload the edited `application.lua` file directly to the NodeMCU hardware using https://github.com/kmpm/nodemcu-uploader or ESPlorer. Reboot the module and the script will automatically compile on the device after reboot.
