### ISSUE TITLE
Instruction to build the firmware

### ISSUE THREAD

**Issue by buzzdev** [konnected-io/konnected-security#85]
Hello,
could you please post instruction how to build the firmware?
Thank you

**Comment by jjok** [comment]
Have you had a look at the `build-firmware` script?

https://github.com/konnected-io/konnected-security/blob/master/scripts/build-firmware

**Comment by buzzdev** [comment]
No i didn't. Thank you for pointing it out.

**Comment by jjok** [comment]
Maybe see if you can add a new section to the README if you work out how to do it?

    git clone ...
    cd konnected-security
    ./scripts/build-firmware

It looks like you need `docker` installed to do the build, so it's worth mentioning that.
